import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DemoEngine,DEMO_KEY} from '../frontend/src/demo/engine.ts';
const blank=()=>btoa('\0'.repeat(512));
function fixture(){let ts=1800000000;const saved=new Map();const storage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)};return {engine:new DemoEngine(storage,blank,()=>ts),storage,advance:n=>ts+=n};}
const command=(s,value,id='request_1234')=>({method:'PUT',body:JSON.stringify({value,expected_version:s.version,request_id:id})});
test('static demo has complete virtual hardware, metrics and a 512-byte OLED frame',()=>{const {engine}=fixture();const s=engine.sample();assert.equal(s.hardware.simulate,true);for(const p of Object.values(s.hardware.connection.components))assert.equal(p.status,'connected');assert.equal(atob(s.applied.oled.pixels).length,512);assert.ok(s.metrics.cpu_fan_rpm>0)});
test('individual LEDs persist across refresh and maintain command conflicts and idempotency',async()=>{const {engine,storage}=fixture(),s=engine.sample(),lights={...s.config.lights,effect:'static',colors:[...s.config.lights.colors]};lights.colors[3]='#ff0033';const req=command(s,lights);const next=await engine.request('/lights',req);assert.equal(next.config.lights.colors[3],'#ff0033');assert.deepEqual(await engine.request('/lights',req),next);await assert.rejects(engine.request('/lights',command(s,lights,'request_next')),{status:409});const reloaded=new DemoEngine(storage,blank);assert.equal(reloaded.sample().config.lights.colors[3],'#ff0033')});
test('fan safety override ignores manual stop at high temperature',async()=>{const {engine}=fixture();let s=engine.sample();await engine.request('/fans/case',command(s,{...s.config.fan,mode:'manual',level:0}));await engine.request('/demo',{method:'PUT',body:JSON.stringify({temperature:78})});s=engine.sample();assert.equal(s.applied.fan.level,10);assert.equal(s.safety_override,true);assert.ok(s.metrics.cpu_fan_rpm>3000)});
test('automatic fan downshift observes a 2-degree margin and 10-second hold',async()=>{const {engine,advance}=fixture();await engine.request('/demo',{method:'PUT',body:JSON.stringify({temperature:68})});assert.equal(engine.sample().applied.fan.level,8);await engine.request('/demo',{method:'PUT',body:JSON.stringify({temperature:38})});assert.equal(engine.sample().applied.fan.level,8);advance(11);assert.equal(engine.sample().applied.fan.level,2)});
test('hardware switches retain config and other components continue working',async()=>{const {engine}=fixture();const s=engine.sample(),h=s.hardware.connection;const next=await engine.request('/hardware',{method:'PUT',body:JSON.stringify({expected_revision:h.revision,value:{...h.config,cube:'off'}})});assert.equal(next.components.fan.status,'disabled');assert.equal(engine.sample().hardware.connection.components.oled.status,'connected');assert.deepEqual(engine.sample().config,s.config);await assert.rejects(engine.request('/hardware',{method:'PUT',body:JSON.stringify({expected_revision:h.revision,value:h.config})}),{status:409})});
test('scenes save, apply, delete; history filters and CSV export work',async()=>{const {engine}=fixture();const s=engine.sample(),config=structuredClone(s.config);config.lights.brightness=23;const saved=await engine.request('/scenes',{method:'POST',body:JSON.stringify({name:'测试场景',config})});let req=command(s,{});req.method='POST';const next=await engine.request(`/scenes/${saved.id}/apply`,req);assert.equal(next.config.lights.brightness,23);assert.equal((await engine.request('/events?kind=scene')).items.length,2);assert.match(await engine.request('/export/events.csv'),/scene.save/);await engine.request(`/scenes/${saved.id}`,{method:'DELETE'});assert.equal((await engine.request('/scenes')).items.length,4)});
test('reset affects demo storage only; corrupt and blocked storage do not crash',async()=>{const {engine,storage}=fixture();storage.setItem('unrelated','keep');await engine.request('/demo/reset',{method:'POST'});assert.equal(storage.getItem('unrelated'),'keep');assert.equal(engine.sample().version,0);storage.setItem(DEMO_KEY,'broken');const restored=new DemoEngine(storage,blank);assert.equal(restored.sample().config.labels.length,14);const blocked=new DemoEngine({getItem:()=>null,setItem:()=>{throw Error('quota')},removeItem:()=>{}},blank);assert.equal(blocked.storageWarning,true);assert.equal(blocked.sample().version,0)});
test('unknown endpoints, real device connections and real token creation are unavailable',async()=>{const {engine}=fixture();await assert.rejects(engine.request('/devices/connect',{method:'POST',body:JSON.stringify({url:'http://192.168.1.1'})}),{status:422});await assert.rejects(engine.request('/tokens',{method:'POST'}),{status:422});await assert.rejects(engine.request('/unknown'),{status:404})});
test('invalid colors and short OLED pixel frames cannot corrupt persisted configuration',async()=>{const {engine}=fixture();const s=engine.sample();await assert.rejects(engine.request('/lights',command(s,{...s.config.lights,colors:['red']})),{status:422});await assert.rejects(engine.request('/oled',command(s,{...s.config.oled,mode:'pixel',pixels:'AAAA'})),{status:422});assert.equal(engine.sample().version,s.version)});
