import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {Fan,Check,RefreshCw,AlertTriangle,ArrowUpRight} from 'lucide-react';
import type {Frame} from './types';
import type {ControlKind,ControlQueue} from './control-queue';

export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={'card '+className}>{children}</section>}
export function Switch({checked,onChange,label,disabled=false}:{checked:boolean;onChange:(v:boolean)=>void;label:string;disabled?:boolean}){return <button type="button" className={'switch '+(checked?'on':'')} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)} disabled={disabled}><span/></button>}
export function OledCanvas({frame,large=false,onPaint}:{frame:Frame|null;large?:boolean;onPaint?:(x:number,y:number)=>void}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d')!;const data=ctx.createImageData(128,32);let bytes='';try{bytes=frame?.pixels?atob(frame.pixels):''}catch{};for(let y=0;y<32;y++)for(let x=0;x<128;x++){const bit=((bytes.charCodeAt(y*16+(x>>3))||0)>>(7-(x%8)))&1;const p=(y*128+x)*4;data.data[p]=bit?213:10;data.data[p+1]=bit?239:21;data.data[p+2]=bit?231:20;data.data[p+3]=255;}ctx.putImageData(data,0,0);},[frame?.pixels]);
 return <canvas ref={ref} width={128} height={32} aria-label={onPaint?'OLED 像素编辑画布':'OLED 最近成功写入的 128×32 位图'} className={'oled-canvas '+(large?'large':'')+(onPaint?' drawable':'')} onPointerDown={e=>{if(!onPaint)return;const r=e.currentTarget.getBoundingClientRect();onPaint(Math.floor((e.clientX-r.left)*128/r.width),Math.floor((e.clientY-r.top)*32/r.height));}}/>;
}
export function FanVisual({level,real=false,rpm=0,size=130}:{level:number;real?:boolean;rpm?:number;size?:number}){const moving=real?rpm>0:level>0;const duration=real?Math.max(.3,1500/Math.max(rpm,1)):Math.max(.35,3-level*.25);return <div className={'fan-visual '+(moving?'moving':'')} style={{width:size,height:size,'--spin':duration+'s','--spin-direction':'normal'} as CSSProperties}><div className="fan-grill"/><div className="fan-rotor"><Fan size={size*.69} strokeWidth={1} className="fan-blades"/></div><div className="fan-hub"/><span className="fan-screw a"/><span className="fan-screw b"/><span className="fan-screw c"/><span className="fan-screw d"/></div>}
export function SectionTitle({eyebrow,title,aside}:{eyebrow?:string;title:string;aside?:ReactNode}){return <div className="section-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{aside}</div>}
export function Pill({children,good=true}:{children:ReactNode;good?:boolean}){return <span className={'pill '+(good?'good':'warn')}><span/>{children}</span>}
export function Empty({children}:{children:ReactNode}){return <div className="empty">{children}</div>}
export function AutoStatus({controls,kind}:{controls:ControlQueue;kind:ControlKind}){const s=controls.status(kind);return <div className={'auto-status '+(s.error?'error':'')} role="status"><span>{s.error?<><AlertTriangle size={14}/>{s.error}</>:s.pending?<><RefreshCw className="spin" size={14}/>{s.offline?'连接恢复后自动生效':'正在生效…'}</>:<><Check size={14}/>调整后自动生效</>}</span>{s.error&&<div>{!s.conflict&&<button className="text-btn" onClick={()=>controls.retry(kind)}>重试</button>}<button className="text-btn" onClick={()=>controls.discard(kind)}>使用设备当前设置</button></div>}</div>}
export function liveDraft<K extends ControlKind>(controls:ControlQueue,kind:K){return {draft:controls.draft(kind),dirty:controls.status(kind).pending,edit:(value:ReturnType<ControlQueue['draft']>,delay=0)=>controls.edit(kind,value,delay)}}
export function Sparkline({values,height=92}:{values:(number|null)[];height?:number}){const good=values.map(x=>x??0);if(good.length<2)return <Empty>正在积累温度记录…</Empty>;const low=Math.min(...good)-3;const high=Math.max(...good)+3;const points=good.map((x,i)=>`${i/(good.length-1)*500},${height-8-(x-low)/(high-low)*(height-16)}`).join(' ');return <svg className="sparkline" viewBox={`0 0 500 ${height}`} role="img" aria-label="CPU 温度变化趋势" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--accent)" stopOpacity=".16"/><stop offset="1" stopColor="var(--accent)" stopOpacity="0"/></linearGradient></defs>{[.25,.5,.75].map(y=><line key={y} x1="0" x2="500" y1={height*y} y2={height*y} stroke="var(--line)" strokeDasharray="3 5"/>)}<polygon points={`0,${height} ${points} 500,${height}`} fill="url(#fade)"/><polyline points={points} fill="none" stroke="var(--accent)" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>}
