import {StrictMode,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,LayoutDashboard,Lightbulb,Fan,Monitor,History,Settings,LogOut,Sun,Moon,Menu,X,RefreshCw,AlertTriangle,Plus,Leaf,Network} from 'lucide-react';
import {api,requestId,watchState} from './api';
import {DEMO,STATIC_DEMO} from './runtime';
import {localDeviceUrl,controllerUrl} from './device-selection';
import {DemoBanner} from './demo/DemoBanner';
import {ControlQueue} from './control-queue';
import {Overview,LightsPage,FansPage,OledPage,HistoryPage,SettingsPage} from './pages';
import type {State,Scene,Metric} from './types';
import './style.css';
import './appearance.css';
import './led.css';
import './case-device.css';
import {useAppearance} from './appearance';
import {DevicesPage,MissingPart,partAvailable} from './DevicesPage';
const nav=[['overview','总览',LayoutDashboard],['lights','灯光',Lightbulb],['fans','风扇',Fan],['oled','OLED 屏幕',Monitor],['devices','设备连接',Network],['history','历史记录',History],['settings','设置',Settings]] as const;
const subtitles:Record<string,string>={overview:'让每一束光、每一阵风，都恰到好处。',lights:'从一颗灯珠，到属于你的整片氛围。',fans:'安静与性能之间，找到合适的平衡。',oled:'把你想看到的，放在触手可及的小屏幕上。',history:'每一次改变，都有迹可循。',devices:'发现树莓派，连接你需要的每个部件。',settings:'为你的设备，保留恰好的掌控。'};

function DeviceSwitch({onLocal}:{onLocal?:()=>void}) {
 const controller=STATIC_DEMO?null:controllerUrl(location.href);
 return <a className="btn small device-switcher" href={controller||'#devices'} onClick={e=>{if(!controller&&onLocal){e.preventDefault();onLocal()}}}><Network size={15}/>切换设备</a>;
}

function Login({onLogin}:{onLogin:()=>void}){const [username,setUsername]=useState('pi');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <div className="login-page"><div className="login-art"><div className="login-orbit one"/><div className="login-orbit two"/><div className="login-emblem"><Fan size={115} strokeWidth={.7}/></div><div className="login-art-copy"><span className="eyebrow">A LITTLE DEVICE. YOUR OWN WORLD.</span><h1>小小设备，<br/>自在掌控。</h1><p>灯光、散热与屏幕，汇聚在一个安静的地方。</p></div><span className="login-dot d1"/><span className="login-dot d2"/><span className="login-dot d3"/></div><div className="login-content"><div className="brand"><span className="brand-icon"><Activity size={21}/></span>Pi Control</div><div className="login-form"><span className="eyebrow">WELCOME HOME</span><h2>欢迎回来</h2><p className="subtle">登录你的树莓派控制中心。</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/auth/login',{method:'POST',body:JSON.stringify({username,password})});setPassword('');onLogin()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="field"><label htmlFor="username">用户名</label><input id="username" name="username" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></div><div className="field"><label htmlFor="password">密码</label><input id="password" name="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div>{error&&<p role="alert" className="error-text">{error}</p>}<button className="btn primary full login-submit" disabled={busy}>{busy?<RefreshCw className="spin" size={17}/>:null}{busy?'正在连接…':'进入控制中心'}<span>↗</span></button></form><div className="login-device-actions"><a className="btn small" href={localDeviceUrl(location.href,true)}>体验演示设备</a>{controllerUrl(location.href)&&<DeviceSwitch/>}</div><div className="login-foot"><span className="live-dot"/>为这台树莓派而生</div></div><span className="login-copyright">PI CONTROL / 01</span></div></div>}

function App(){const [state,setState]=useState<State|null>(null);const [loggedOut,setLoggedOut]=useState(false);const [tab,setTab]=useState(location.hash==='#devices'?'devices':'overview');const [focusLed,setFocusLed]=useState<number|undefined>(undefined);const [connected,setConnected]=useState(false);const [busy,setBusy]=useState(false);const [toast,setToast]=useState('');const [scenes,setScenes]=useState<Scene[]>([]);const [metrics,setMetrics]=useState<Metric[]>([]);const appearance=useAppearance();const [mobile,setMobile]=useState(false);const [saveOpen,setSaveOpen]=useState(false);const [sceneName,setSceneName]=useState('');const [bootError,setBootError]=useState('');
 const [controls]=useState(()=>new ControlQueue({read:()=>api<State>('/status'),send:(kind,body)=>api<State>(kind==='fan'?'/fans/case':'/'+kind,{method:'PUT',body:JSON.stringify(body)})}));
 const [,redrawControls]=useState(0);
 useEffect(()=>controls.subscribe(()=>{setState(controls.state);redrawControls(n=>n+1)}),[controls]);
 const notice=(message:string)=>setToast(message);
 const refreshScenes=()=>api('/scenes').then(r=>setScenes(r.items)).catch(e=>notice(e.message));
 const load=async()=>{try{const s=await api<State>('/status');controls.accept(s);setLoggedOut(false);setBootError('');refreshScenes();api('/metrics?hours=1').then(r=>setMetrics(r.items)).catch(()=>{})}catch(e){if((e as any).status===401){setLoggedOut(true);controls.clear();setState(null)}else setBootError((e as Error).message)}};
 useEffect(()=>{load();const change=()=>{if(location.hash==='#devices')setTab('devices')};const openDevices=()=>setTab('devices');window.addEventListener('hashchange',change);window.addEventListener('pi-control:devices',openDevices);return()=>{window.removeEventListener('hashchange',change);window.removeEventListener('pi-control:devices',openDevices)}},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(timer)},[toast]);
 useEffect(()=>{if(!state||loggedOut)return;const stop=watchState(s=>controls.accept(s),v=>{setConnected(v);controls.setConnected(v)},()=>{setLoggedOut(true);controls.clear();setState(null)});const interval=setInterval(()=>{api('/metrics?hours=1').then(r=>setMetrics(r.items)).catch(()=>{})},30000);return()=>{stop();clearInterval(interval)}},[!!state,loggedOut]);
 const applyScene=async(id:string)=>{if(!state||!connected||controls.active)return;setBusy(true);try{const next=await api<State>(`/scenes/${id}/apply`,{method:'POST',body:JSON.stringify({value:{},expected_version:state.version,request_id:requestId()})});controls.accept(next);notice('场景已应用')}catch(e){notice((e as Error).message);load()}finally{setBusy(false)}};
 if(loggedOut)return <Login onLogin={load}/>;
 if(!state)return <div className="loading-page"><Activity size={35}/><h2>Pi Control</h2><p>{bootError||(DEMO?'正在准备交互演示…':'正在连接你的树莓派…')}</p>{bootError&&<button className="btn primary" onClick={load}>重试连接</button>}</div>;
 const props={state,busy:busy||!connected,controls,notice};
 return <div className="app-shell"><aside className={'sidebar '+(mobile?'open':'')}><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('overview')}}><span className="brand-icon"><Activity size={21}/></span>Pi Control</a><div className="sidebar-label">你的设备空间</div><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMobile(false)}}><Icon size={19} strokeWidth={1.8}/><span>{label}</span>{tab===id&&<i/>}</button>)}</nav><div className="sidebar-bottom"><div className="host-card"><div className="host-icon"><Leaf size={21}/></div><div><b>{state.device?.name||'树莓派'}</b><small><span className={'live-dot '+(!connected?'offline':'')}/>{connected?(state.hardware.simulate?'模拟运行':'已连接'):'连接中…'}</small></div></div><div className="sidebar-actions"><button className="icon-btn" aria-label="切换深浅主题" onClick={()=>appearance.setMode(appearance.resolved==='light'?'dark':'light')}>{appearance.resolved==='light'?<Moon size={17}/>:<Sun size={17}/>}</button><span>v1.5.0</span>{!DEMO&&!state.demo&&<button className="icon-btn" aria-label="退出登录" onClick={()=>api('/auth/logout',{method:'POST'}).then(()=>{setLoggedOut(true);controls.clear();setState(null)}).catch(e=>notice(e.message))}><LogOut size={17}/></button>}</div></div></aside>{mobile&&<button className="mobile-scrim" aria-label="关闭导航" onClick={()=>setMobile(false)}/>}
 <main><header className="topbar"><div><button className="icon-btn mobile-menu" aria-label="打开导航" onClick={()=>setMobile(!mobile)}><Menu size={21}/></button><span className="breadcrumb">我的设备 <span>/</span> {state.device?.name||'树莓派'}</span></div><div className="topbar-right"><DeviceSwitch onLocal={()=>{setTab('devices');setMobile(false)}}/><span className={'connection '+(connected?'':'offline')}><span/>{connected?(state.hardware.simulate?'实时模拟':'实时连接'):'状态可能过期'}</span><span className="avatar">P</span></div></header><div className="main-content"><div className="page-heading"><div><span className="eyebrow">{tab==='overview'?'YOUR DEVICE, IN HARMONY.':'PI CONTROL / '+tab.toUpperCase()}</span><h1>{tab==='overview'?'你好，树莓派。':nav.find(x=>x[0]===tab)?.[1]}</h1><p>{subtitles[tab]}</p></div>{tab==='overview'&&<button className="btn" onClick={()=>setSaveOpen(true)}><Plus size={16}/>保存为场景</button>}</div>
 {!connected&&<div className="warning" role="status"><AlertTriangle size={17}/>实时连接已断开，正在重新连接；待生效的调整会在连接恢复后继续发送。</div>}
 {DEMO&&<DemoBanner/>}
 {!DEMO&&state.hardware.simulate&&<div className="warning">当前选择演示设备，灯光、风扇和屏幕均为模拟。<button className="btn small" onClick={()=>setTab('devices')}>选择设备</button></div>}
 {Object.keys(state.hardware.errors).length>0&&<div className="warning" role="alert"><AlertTriangle size={17}/><span>硬件通信需要关注：{Object.entries(state.hardware.errors).map(([k,v])=>`${k}: ${v}`).join('；')}。页面保留最近成功写入的状态。</span></div>}
 {tab==='overview'&&<Overview state={state} busy={props.busy||controls.active} scenes={scenes} applyScene={applyScene} navigate={setTab} metrics={metrics} onSave={()=>setSaveOpen(true)} pickLight={i=>{setFocusLed(i);setTab('lights')}}/>}
 {tab==='lights'&&(partAvailable(state,'lights')?<LightsPage {...props} initialSelection={focusLed}/>:<MissingPart state={state} kind="lights" name="RGB 灯条"/>)}{tab==='fans'&&<FansPage {...props}/>}{tab==='oled'&&(partAvailable(state,'oled')?<OledPage {...props}/>:<MissingPart state={state} kind="oled" name="OLED 屏幕"/>)}{tab==='devices'&&<DevicesPage state={state} notice={notice}/>}{tab==='history'&&<HistoryPage notice={notice}/>}{tab==='settings'&&<SettingsPage appearance={appearance} state={state} notice={notice} scenes={scenes} refreshScenes={refreshScenes} applyScene={applyScene} busy={props.busy||controls.active}/>}
 <footer className="page-footer"><span>PI CONTROL</span><span>{state.hardware.simulate?'演示数据 · 控制操作不会发送到硬件':'硬件状态以最近成功写入和实际传感器读数为准'}</span></footer></div></main>
 {toast&&<div className="toast" role="status"><span>{toast}</span><button aria-label="关闭提示" onClick={()=>setToast('')}><X size={15}/></button></div>}
 {saveOpen&&<div className="modal-backdrop" onClick={()=>setSaveOpen(false)}><section className="modal card" role="dialog" aria-modal="true" aria-labelledby="save-title" onClick={e=>e.stopPropagation()}><div className="modal-title"><h2 id="save-title">保存这一刻</h2><button className="icon-btn" aria-label="关闭" onClick={()=>setSaveOpen(false)}><X size={19}/></button></div><p className="subtle">保存当前灯光、风扇和 OLED 设置，下次一键恢复。</p><div className="field"><label>场景名称</label><input autoFocus maxLength={30} placeholder="例如：夜间阅读" value={sceneName} onChange={e=>setSceneName(e.target.value)}/></div><button className="btn primary full" disabled={!sceneName.trim()||busy} onClick={async()=>{setBusy(true);try{await api('/scenes',{method:'POST',body:JSON.stringify({name:sceneName.trim(),icon:'custom',config:state.config})});setSaveOpen(false);setSceneName('');refreshScenes();notice('场景已保存')}catch(e){notice((e as Error).message)}finally{setBusy(false)}}}>保存场景</button></section></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
